server:
  port: 8080
  servlet :
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret_key: werwkjrkdfkajsdfjwqerjsdjflsafjlaksrfjwepqrjqwjkfsdkfjasdf